framework:
    cache:
        default_redis_provider: '%env(CACHE_REDIS_URL)%'

        system: cache.adapter.redis
        app: cache.adapter.apcu

        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system

            app.core:
                adapter: cache.app
