doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        dql:
            string_functions:
                DAY: DoctrineExtensions\Query\Postgresql\Day
                MONTH: DoctrineExtensions\Query\Postgresql\Month
                YEAR: DoctrineExtensions\Query\Postgresql\Year
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        resolve_target_entities:
            Parthenon\User\Entity\UserInterface: App\Entity\User
            Parthenon\User\Entity\TeamInterface: App\Entity\User
            Parthenon\Billing\Entity\CustomerInterface: App\Entity\Customer
            Parthenon\Billing\Entity\BillingAdminInterface: App\Entity\User
            Parthenon\Billing\Entity\PaymentInterface: App\Entity\Payment
            Parthenon\Billing\Entity\ProductInterface: App\Entity\Product
            Parthenon\Billing\Entity\PriceInterface: App\Entity\Price
            Parthenon\Billing\Entity\ReceiptInterface: App\Entity\Receipt
            Parthenon\Billing\Entity\ReceiptLineInterface: App\Entity\ReceiptLine
            Parthenon\Billing\Entity\SubscriptionInterface: App\Entity\Subscription
            Parthenon\Billing\Entity\SubscriptionPlanInterface: App\Entity\SubscriptionPlan
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/App/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
