version: '3.2'

services:
  mail:
    image: bytemark/smtp
    restart: always
    networks:
      - billabear

  redis:
    image: redis:5-alpine
    networks:
      - billabear
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:8.17.1
    deploy:
      resources:
        limits:
          memory: "2g"
        reservations:
          memory: "1g"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - billabear

  database:
    image: timescale/timescaledb-ha:pg17
    environment:
      - POSTGRES_DB=${PSQGL_DATABASE_NAME}
      - POSTGRES_USER=${PSQGL_DATABASE_USER}
      - POSTGRES_PASSWORD=${PSQGL_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/database/data:/home/postgres/pgdata/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - billabear

  php-fpm:
    image: billabear/ubuntu-php-fpm:8.4
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=pgsql://${PSQGL_DATABASE_USER}:${PSQGL_DATABASE_PASSWORD}@database:5432/${PSQGL_DATABASE_NAME}
    volumes:
      - .:/var/www
    networks:
      - billabear

  nginx:
    image: getparthenon/ubuntu-nginx:21.04
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    networks:
      - billabear

networks:
  billabear:
    driver: bridge
