<?php

declare(strict_types=1);

/*
 * Copyright Humbly Arrogant Software Limited 2023.
 *
 * Use of this software is governed by the Business Source License included in the LICENSE file and at https://github.com/BillaBear/billabear/blob/main/LICENSE.
 *
 * Change Date: 09.10.2026 ( 3 years after 2023.4 release )
 *
 * On the date above, in accordance with the Business Source License, use of this software will be governed by the open source license specified in the LICENSE file.
 */

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20231011214508 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE api_key (id UUID NOT NULL, name VARCHAR(255) NOT NULL, key VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX api_key_idx ON api_key (key)');
        $this->addSql('COMMENT ON COLUMN api_key.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE brand_settings (id UUID NOT NULL, code VARCHAR(255) NOT NULL, brand_name VARCHAR(255) NOT NULL, email_address VARCHAR(255) NOT NULL, is_default BOOLEAN NOT NULL, tax_number VARCHAR(255) DEFAULT NULL, tax_rate DOUBLE PRECISION DEFAULT NULL, digital_services_rate DOUBLE PRECISION DEFAULT NULL, address_company_name VARCHAR(255) DEFAULT NULL, address_street_line_one VARCHAR(255) DEFAULT NULL, address_street_line_two VARCHAR(255) DEFAULT NULL, address_city VARCHAR(255) DEFAULT NULL, address_region VARCHAR(255) DEFAULT NULL, address_country VARCHAR(255) DEFAULT NULL, address_postcode VARCHAR(255) DEFAULT NULL, notification_settings_subscription_creation BOOLEAN DEFAULT NULL, notification_settings_subscription_cancellation BOOLEAN DEFAULT NULL, notification_settings_expiring_card_warning BOOLEAN DEFAULT NULL, notification_settings_expiring_card_day_before BOOLEAN DEFAULT NULL, notification_settings_invoice_created BOOLEAN DEFAULT NULL, notification_settings_invoice_overdue BOOLEAN DEFAULT NULL, notification_settings_quote_created BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_227533D477153098 ON brand_settings (code)');
        $this->addSql('CREATE INDEX brand_code_idx ON brand_settings (code)');
        $this->addSql('COMMENT ON COLUMN brand_settings.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE cancellation_requests (id UUID NOT NULL, subscription_id UUID DEFAULT NULL, billing_admin_id UUID DEFAULT NULL, state VARCHAR(255) NOT NULL, when_to_cancel VARCHAR(255) NOT NULL, specific_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, refund_type VARCHAR(255) NOT NULL, comment VARCHAR(255) DEFAULT NULL, original_valid_until TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, error TEXT DEFAULT NULL, has_error BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9E258B3E9A1887DC ON cancellation_requests (subscription_id)');
        $this->addSql('CREATE INDEX IDX_9E258B3E7CF7EBEC ON cancellation_requests (billing_admin_id)');
        $this->addSql('COMMENT ON COLUMN cancellation_requests.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN cancellation_requests.subscription_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN cancellation_requests.billing_admin_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE charge_back (id UUID NOT NULL, payment_id UUID DEFAULT NULL, customer_id UUID DEFAULT NULL, external_reference VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, reason VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_250DACE84C3A3BB ON charge_back (payment_id)');
        $this->addSql('CREATE INDEX IDX_250DACE89395C3F3 ON charge_back (customer_id)');
        $this->addSql('COMMENT ON COLUMN charge_back.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN charge_back.payment_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN charge_back.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE charge_back_creation (id UUID NOT NULL, charge_back_id UUID DEFAULT NULL, state VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, error VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3394E461BDB3CB55 ON charge_back_creation (charge_back_id)');
        $this->addSql('COMMENT ON COLUMN charge_back_creation.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN charge_back_creation.charge_back_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE checkout (id UUID NOT NULL, customer_id UUID DEFAULT NULL, brand_settings_id UUID DEFAULT NULL, created_by_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, permanent BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, currency VARCHAR(255) NOT NULL, success_redirect VARCHAR(255) DEFAULT NULL, cancel_redirect VARCHAR(255) DEFAULT NULL, amount_due INT DEFAULT NULL, total INT DEFAULT NULL, sub_total INT DEFAULT NULL, tax_total INT DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AF382D4E9395C3F3 ON checkout (customer_id)');
        $this->addSql('CREATE INDEX IDX_AF382D4E38C5B87D ON checkout (brand_settings_id)');
        $this->addSql('CREATE INDEX IDX_AF382D4EB03A8386 ON checkout (created_by_id)');
        $this->addSql('COMMENT ON COLUMN checkout.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN checkout.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN checkout.brand_settings_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN checkout.created_by_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE checkout_line (id UUID NOT NULL, checkout_id UUID DEFAULT NULL, subscription_plan_id UUID DEFAULT NULL, price_id UUID DEFAULT NULL, seat_number INT DEFAULT NULL, currency VARCHAR(255) NOT NULL, total INT DEFAULT NULL, sub_total INT DEFAULT NULL, tax_total INT DEFAULT NULL, tax_percentage DOUBLE PRECISION DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, tax_type VARCHAR(255) DEFAULT NULL, include_tax BOOLEAN NOT NULL, tax_country VARCHAR(255) DEFAULT NULL, reverse_charge BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3A4D4128146D8724 ON checkout_line (checkout_id)');
        $this->addSql('CREATE INDEX IDX_3A4D41289B8CE200 ON checkout_line (subscription_plan_id)');
        $this->addSql('CREATE INDEX IDX_3A4D4128D614C7E7 ON checkout_line (price_id)');
        $this->addSql('COMMENT ON COLUMN checkout_line.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN checkout_line.checkout_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN checkout_line.subscription_plan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN checkout_line.price_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE checkout_session (id UUID NOT NULL, customer_id UUID DEFAULT NULL, checkout_id UUID DEFAULT NULL, currency VARCHAR(255) NOT NULL, amount_due INT DEFAULT NULL, total INT DEFAULT NULL, sub_total INT DEFAULT NULL, tax_total INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paid BOOLEAN NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2C2F31AD9395C3F3 ON checkout_session (customer_id)');
        $this->addSql('CREATE INDEX IDX_2C2F31AD146D8724 ON checkout_session (checkout_id)');
        $this->addSql('COMMENT ON COLUMN checkout_session.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN checkout_session.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN checkout_session.checkout_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE checkout_session_subscription (checkout_session_id UUID NOT NULL, subscription_id UUID NOT NULL, PRIMARY KEY(checkout_session_id, subscription_id))');
        $this->addSql('CREATE INDEX IDX_622CEAC2DA6D31C4 ON checkout_session_subscription (checkout_session_id)');
        $this->addSql('CREATE INDEX IDX_622CEAC29A1887DC ON checkout_session_subscription (subscription_id)');
        $this->addSql('COMMENT ON COLUMN checkout_session_subscription.checkout_session_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN checkout_session_subscription.subscription_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE checkout_session_line (id UUID NOT NULL, checkout_session_id UUID DEFAULT NULL, subscription_plan_id UUID DEFAULT NULL, price_id UUID DEFAULT NULL, seat_number INT DEFAULT NULL, currency VARCHAR(255) NOT NULL, total INT DEFAULT NULL, sub_total INT DEFAULT NULL, tax_total INT DEFAULT NULL, tax_percentage DOUBLE PRECISION DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, tax_type VARCHAR(255) DEFAULT NULL, include_tax BOOLEAN NOT NULL, tax_country VARCHAR(255) DEFAULT NULL, reverse_charge BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_46316A7DDA6D31C4 ON checkout_session_line (checkout_session_id)');
        $this->addSql('CREATE INDEX IDX_46316A7D9B8CE200 ON checkout_session_line (subscription_plan_id)');
        $this->addSql('CREATE INDEX IDX_46316A7DD614C7E7 ON checkout_session_line (price_id)');
        $this->addSql('COMMENT ON COLUMN checkout_session_line.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN checkout_session_line.checkout_session_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN checkout_session_line.subscription_plan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN checkout_session_line.price_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE credit (id UUID NOT NULL, customer_id UUID DEFAULT NULL, billing_admin_id UUID DEFAULT NULL, type VARCHAR(255) NOT NULL, creation_type VARCHAR(255) NOT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, used_amount INT NOT NULL, completely_used BOOLEAN NOT NULL, reason VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, valid_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1CC16EFE7CF7EBEC ON credit (billing_admin_id)');
        $this->addSql('CREATE INDEX customer_idx ON credit (customer_id)');
        $this->addSql('COMMENT ON COLUMN credit.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN credit.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN credit.billing_admin_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE customers (id UUID NOT NULL, brand_settings_id UUID DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, external_customer_reference VARCHAR(255) NOT NULL, billing_email VARCHAR(255) DEFAULT NULL, billing_type VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, brand VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, payment_provider_details_url VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, disabled BOOLEAN DEFAULT NULL, credit_amount INT DEFAULT NULL, credit_currency VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tax_number VARCHAR(255) DEFAULT NULL, tax_exempt BOOLEAN DEFAULT NULL, tax_rate_digital DOUBLE PRECISION DEFAULT NULL, tax_rate_standard DOUBLE PRECISION DEFAULT NULL, type VARCHAR(255) NOT NULL, billing_address_company_name VARCHAR(255) DEFAULT NULL, billing_address_street_line_one VARCHAR(255) DEFAULT NULL, billing_address_street_line_two VARCHAR(255) DEFAULT NULL, billing_address_city VARCHAR(255) DEFAULT NULL, billing_address_region VARCHAR(255) DEFAULT NULL, billing_address_country VARCHAR(255) DEFAULT NULL, billing_address_postcode VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_62534E2138C5B87D ON customers (brand_settings_id)');
        $this->addSql('CREATE INDEX email_idx ON customers (billing_email)');
        $this->addSql('CREATE INDEX external_ref_idx ON customers (external_customer_reference)');
        $this->addSql('COMMENT ON COLUMN customers.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN customers.brand_settings_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE email_templates (id UUID NOT NULL, brand_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, subject VARCHAR(255) DEFAULT NULL, use_emsp_template BOOLEAN NOT NULL, template_id VARCHAR(255) DEFAULT NULL, template_body TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6023E2A544F5D008 ON email_templates (brand_id)');
        $this->addSql('CREATE INDEX name_locale ON email_templates (name, locale)');
        $this->addSql('CREATE UNIQUE INDEX name_locale_brand ON email_templates (name, locale, brand_id)');
        $this->addSql('COMMENT ON COLUMN email_templates.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN email_templates.brand_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE exchange_rates (id UUID NOT NULL, currency_code VARCHAR(255) NOT NULL, exchange_rate VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5AE3E774FDA273EC ON exchange_rates (currency_code)');
        $this->addSql('CREATE INDEX ex_rates_currency_code_idx ON exchange_rates (currency_code)');
        $this->addSql('COMMENT ON COLUMN exchange_rates.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE expiring_card_process (id UUID NOT NULL, customer_id UUID DEFAULT NULL, payment_card_id UUID DEFAULT NULL, state VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subscription_charged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, error VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CD6C5DF9395C3F3 ON expiring_card_process (customer_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CD6C5DF538594CA ON expiring_card_process (payment_card_id)');
        $this->addSql('COMMENT ON COLUMN expiring_card_process.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN expiring_card_process.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN expiring_card_process.payment_card_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE forgot_password_code (id UUID NOT NULL, user_id UUID DEFAULT NULL, code VARCHAR(255) NOT NULL, used BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B30A7571A76ED395 ON forgot_password_code (user_id)');
        $this->addSql('COMMENT ON COLUMN forgot_password_code.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN forgot_password_code.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE generic_background_task (id UUID NOT NULL, status VARCHAR(255) NOT NULL, task VARCHAR(255) NOT NULL, meta JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B747BA407B00651C ON generic_background_task (status)');
        $this->addSql('COMMENT ON COLUMN generic_background_task.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE invite_codes (id UUID NOT NULL, user_id UUID DEFAULT NULL, invited_user_id UUID DEFAULT NULL, code VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, used BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancelled BOOLEAN NOT NULL, role VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E8D89FB2A76ED395 ON invite_codes (user_id)');
        $this->addSql('CREATE INDEX IDX_E8D89FB2C58DAD6E ON invite_codes (invited_user_id)');
        $this->addSql('COMMENT ON COLUMN invite_codes.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN invite_codes.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN invite_codes.invited_user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE invoice (id UUID NOT NULL, customer_id UUID DEFAULT NULL, invoice_number VARCHAR(255) NOT NULL, valid BOOLEAN NOT NULL, comment VARCHAR(255) DEFAULT NULL, currency VARCHAR(255) NOT NULL, amount_due INT NOT NULL, total INT NOT NULL, sub_total INT NOT NULL, tax_total INT NOT NULL, paid BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, due_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, biller_address_company_name VARCHAR(255) DEFAULT NULL, biller_address_street_line_one VARCHAR(255) DEFAULT NULL, biller_address_street_line_two VARCHAR(255) DEFAULT NULL, biller_address_city VARCHAR(255) DEFAULT NULL, biller_address_region VARCHAR(255) DEFAULT NULL, biller_address_country VARCHAR(255) DEFAULT NULL, biller_address_postcode VARCHAR(255) DEFAULT NULL, payee_address_company_name VARCHAR(255) DEFAULT NULL, payee_address_street_line_one VARCHAR(255) DEFAULT NULL, payee_address_street_line_two VARCHAR(255) DEFAULT NULL, payee_address_city VARCHAR(255) DEFAULT NULL, payee_address_region VARCHAR(255) DEFAULT NULL, payee_address_country VARCHAR(255) DEFAULT NULL, payee_address_postcode VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_906517442DA68207 ON invoice (invoice_number)');
        $this->addSql('CREATE INDEX IDX_906517449395C3F3 ON invoice (customer_id)');
        $this->addSql('COMMENT ON COLUMN invoice.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN invoice.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE invoice_subscription (invoice_id UUID NOT NULL, subscription_id UUID NOT NULL, PRIMARY KEY(invoice_id, subscription_id))');
        $this->addSql('CREATE INDEX IDX_1C014BA72989F1FD ON invoice_subscription (invoice_id)');
        $this->addSql('CREATE INDEX IDX_1C014BA79A1887DC ON invoice_subscription (subscription_id)');
        $this->addSql('COMMENT ON COLUMN invoice_subscription.invoice_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN invoice_subscription.subscription_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE invoice_payment (invoice_id UUID NOT NULL, payment_id UUID NOT NULL, PRIMARY KEY(invoice_id, payment_id))');
        $this->addSql('CREATE INDEX IDX_9FF1B2DE2989F1FD ON invoice_payment (invoice_id)');
        $this->addSql('CREATE INDEX IDX_9FF1B2DE4C3A3BB ON invoice_payment (payment_id)');
        $this->addSql('COMMENT ON COLUMN invoice_payment.invoice_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN invoice_payment.payment_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE invoice_line (id UUID NOT NULL, invoice_id UUID DEFAULT NULL, currency VARCHAR(255) NOT NULL, total INT NOT NULL, sub_total INT NOT NULL, tax_total INT NOT NULL, tax_percentage DOUBLE PRECISION DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, tax_type VARCHAR(255) DEFAULT NULL, tax_country VARCHAR(255) DEFAULT NULL, reverse_charge BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D3D1D6932989F1FD ON invoice_line (invoice_id)');
        $this->addSql('COMMENT ON COLUMN invoice_line.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN invoice_line.invoice_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE invoice_process (id UUID NOT NULL, customer_id UUID DEFAULT NULL, invoice_id UUID DEFAULT NULL, state VARCHAR(255) NOT NULL, due_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, error VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_74C42E459395C3F3 ON invoice_process (customer_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_74C42E452989F1FD ON invoice_process (invoice_id)');
        $this->addSql('COMMENT ON COLUMN invoice_process.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN invoice_process.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN invoice_process.invoice_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE mass_subscription_change (id UUID NOT NULL, target_subscription_plan_id UUID DEFAULT NULL, new_subscription_plan_id UUID DEFAULT NULL, target_price_id UUID DEFAULT NULL, new_price_id UUID DEFAULT NULL, brand_settings_id UUID DEFAULT NULL, created_by_id UUID DEFAULT NULL, change_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, target_country VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A63C0CACF1B966A3 ON mass_subscription_change (target_subscription_plan_id)');
        $this->addSql('CREATE INDEX IDX_A63C0CAC6C4D9255 ON mass_subscription_change (new_subscription_plan_id)');
        $this->addSql('CREATE INDEX IDX_A63C0CACCBF178E ON mass_subscription_change (target_price_id)');
        $this->addSql('CREATE INDEX IDX_A63C0CAC917D4BCB ON mass_subscription_change (new_price_id)');
        $this->addSql('CREATE INDEX IDX_A63C0CAC38C5B87D ON mass_subscription_change (brand_settings_id)');
        $this->addSql('CREATE INDEX IDX_A63C0CACB03A8386 ON mass_subscription_change (created_by_id)');
        $this->addSql('COMMENT ON COLUMN mass_subscription_change.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN mass_subscription_change.target_subscription_plan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN mass_subscription_change.new_subscription_plan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN mass_subscription_change.target_price_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN mass_subscription_change.new_price_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN mass_subscription_change.brand_settings_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN mass_subscription_change.created_by_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE parthenon_export_background_export_requests (id UUID NOT NULL, exported_file VARCHAR(255) DEFAULT NULL, exported_file_path VARCHAR(255) DEFAULT NULL, export_format VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, data_provider_service VARCHAR(255) NOT NULL, data_provider_parameters JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN parthenon_export_background_export_requests.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE payment (id UUID NOT NULL, customer_id UUID DEFAULT NULL, invoice_id UUID DEFAULT NULL, provider VARCHAR(255) NOT NULL, payment_reference VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, refunded BOOLEAN NOT NULL, completed BOOLEAN NOT NULL, charged_back BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, payment_provider_details_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6D28840D9395C3F3 ON payment (customer_id)');
        $this->addSql('CREATE INDEX IDX_6D28840D2989F1FD ON payment (invoice_id)');
        $this->addSql('COMMENT ON COLUMN payment.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN payment.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN payment.invoice_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE payment_subscription (payment_id UUID NOT NULL, subscription_id UUID NOT NULL, PRIMARY KEY(payment_id, subscription_id))');
        $this->addSql('CREATE INDEX IDX_C536D3C94C3A3BB ON payment_subscription (payment_id)');
        $this->addSql('CREATE INDEX IDX_C536D3C99A1887DC ON payment_subscription (subscription_id)');
        $this->addSql('COMMENT ON COLUMN payment_subscription.payment_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN payment_subscription.subscription_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE payment_attempt (id UUID NOT NULL, customer_id UUID DEFAULT NULL, invoice_id UUID DEFAULT NULL, failure_reason VARCHAR(255) NOT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1A50C8C2989F1FD ON payment_attempt (invoice_id)');
        $this->addSql('CREATE INDEX IDX_1A50C8C9395C3F3 ON payment_attempt (customer_id)');
        $this->addSql('COMMENT ON COLUMN payment_attempt.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN payment_attempt.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN payment_attempt.invoice_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE payment_attempt_subscription (payment_attempt_id UUID NOT NULL, subscription_id UUID NOT NULL, PRIMARY KEY(payment_attempt_id, subscription_id))');
        $this->addSql('CREATE INDEX IDX_A9AFAA2384673FBE ON payment_attempt_subscription (payment_attempt_id)');
        $this->addSql('CREATE INDEX IDX_A9AFAA239A1887DC ON payment_attempt_subscription (subscription_id)');
        $this->addSql('COMMENT ON COLUMN payment_attempt_subscription.payment_attempt_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN payment_attempt_subscription.subscription_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE payment_card (id UUID NOT NULL, customer_id UUID DEFAULT NULL, provider VARCHAR(255) DEFAULT NULL, stored_customer_reference VARCHAR(255) DEFAULT NULL, stored_payment_reference VARCHAR(255) DEFAULT NULL, default_payment_option BOOLEAN NOT NULL, brand VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, last_four VARCHAR(255) DEFAULT NULL, expiry_month VARCHAR(255) DEFAULT NULL, expiry_year VARCHAR(255) DEFAULT NULL, is_deleted BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_37970FA79395C3F3 ON payment_card (customer_id)');
        $this->addSql('COMMENT ON COLUMN payment_card.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN payment_card.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE payment_creation (id UUID NOT NULL, payment_id UUID DEFAULT NULL, state VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, error VARCHAR(255) DEFAULT NULL, has_error BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1728C71C4C3A3BB ON payment_creation (payment_id)');
        $this->addSql('COMMENT ON COLUMN payment_creation.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN payment_creation.payment_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE payment_failure_process (id UUID NOT NULL, payment_attempt_id UUID DEFAULT NULL, customer_id UUID DEFAULT NULL, state VARCHAR(255) NOT NULL, retry_count INT NOT NULL, resolved BOOLEAN NOT NULL, next_attempt_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F939A84884673FBE ON payment_failure_process (payment_attempt_id)');
        $this->addSql('CREATE INDEX IDX_F939A8489395C3F3 ON payment_failure_process (customer_id)');
        $this->addSql('CREATE INDEX IDX_F939A8489395C3F3A393D2FB ON payment_failure_process (customer_id, state)');
        $this->addSql('CREATE INDEX IDX_F939A848A393D2FBDB68CFC4 ON payment_failure_process (state, next_attempt_at)');
        $this->addSql('COMMENT ON COLUMN payment_failure_process.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN payment_failure_process.payment_attempt_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN payment_failure_process.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE price (id UUID NOT NULL, product_id UUID DEFAULT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, recurring BOOLEAN DEFAULT NULL, public BOOLEAN DEFAULT NULL, is_deleted BOOLEAN DEFAULT NULL, schedule VARCHAR(255) DEFAULT NULL, external_reference VARCHAR(255) DEFAULT NULL, payment_provider_details_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CAC822D94584665A ON price (product_id)');
        $this->addSql('COMMENT ON COLUMN price.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN price.product_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE product (id UUID NOT NULL, name VARCHAR(255) NOT NULL, payment_provider_details_url VARCHAR(255) DEFAULT NULL, external_reference VARCHAR(255) DEFAULT NULL, tax_type VARCHAR(255) NOT NULL, tax_rate DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN product.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE quote (id UUID NOT NULL, customer_id UUID DEFAULT NULL, created_by_id UUID DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, currency VARCHAR(255) NOT NULL, amount_due INT NOT NULL, total INT NOT NULL, sub_total INT NOT NULL, tax_total INT NOT NULL, paid BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6B71CBF49395C3F3 ON quote (customer_id)');
        $this->addSql('CREATE INDEX IDX_6B71CBF4B03A8386 ON quote (created_by_id)');
        $this->addSql('COMMENT ON COLUMN quote.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN quote.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN quote.created_by_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE quote_subscription (quote_id UUID NOT NULL, subscription_id UUID NOT NULL, PRIMARY KEY(quote_id, subscription_id))');
        $this->addSql('CREATE INDEX IDX_14273BD5DB805178 ON quote_subscription (quote_id)');
        $this->addSql('CREATE INDEX IDX_14273BD59A1887DC ON quote_subscription (subscription_id)');
        $this->addSql('COMMENT ON COLUMN quote_subscription.quote_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN quote_subscription.subscription_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE quote_line (id UUID NOT NULL, quote_id UUID DEFAULT NULL, subscription_plan_id UUID DEFAULT NULL, price_id UUID DEFAULT NULL, seat_number INT DEFAULT NULL, currency VARCHAR(255) NOT NULL, total INT NOT NULL, sub_total INT NOT NULL, tax_total INT NOT NULL, tax_percentage DOUBLE PRECISION DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, tax_type VARCHAR(255) DEFAULT NULL, include_tax BOOLEAN NOT NULL, tax_country VARCHAR(255) DEFAULT NULL, reverse_charge BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_43F3EB7CDB805178 ON quote_line (quote_id)');
        $this->addSql('CREATE INDEX IDX_43F3EB7C9B8CE200 ON quote_line (subscription_plan_id)');
        $this->addSql('CREATE INDEX IDX_43F3EB7CD614C7E7 ON quote_line (price_id)');
        $this->addSql('COMMENT ON COLUMN quote_line.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN quote_line.quote_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN quote_line.subscription_plan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN quote_line.price_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE receipt (id UUID NOT NULL, customer_id UUID DEFAULT NULL, valid BOOLEAN NOT NULL, currency VARCHAR(255) NOT NULL, total INT NOT NULL, sub_total INT NOT NULL, vat_total INT NOT NULL, comment VARCHAR(255) DEFAULT NULL, vat_percentage DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, biller_address_company_name VARCHAR(255) DEFAULT NULL, biller_address_street_line_one VARCHAR(255) DEFAULT NULL, biller_address_street_line_two VARCHAR(255) DEFAULT NULL, biller_address_city VARCHAR(255) DEFAULT NULL, biller_address_region VARCHAR(255) DEFAULT NULL, biller_address_country VARCHAR(255) DEFAULT NULL, biller_address_postcode VARCHAR(255) DEFAULT NULL, payee_address_company_name VARCHAR(255) DEFAULT NULL, payee_address_street_line_one VARCHAR(255) DEFAULT NULL, payee_address_street_line_two VARCHAR(255) DEFAULT NULL, payee_address_city VARCHAR(255) DEFAULT NULL, payee_address_region VARCHAR(255) DEFAULT NULL, payee_address_country VARCHAR(255) DEFAULT NULL, payee_address_postcode VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5399B6459395C3F3 ON receipt (customer_id)');
        $this->addSql('COMMENT ON COLUMN receipt.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN receipt.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE receipt_payment (receipt_id UUID NOT NULL, payment_id UUID NOT NULL, PRIMARY KEY(receipt_id, payment_id))');
        $this->addSql('CREATE INDEX IDX_7E6221F32B5CA896 ON receipt_payment (receipt_id)');
        $this->addSql('CREATE INDEX IDX_7E6221F34C3A3BB ON receipt_payment (payment_id)');
        $this->addSql('COMMENT ON COLUMN receipt_payment.receipt_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN receipt_payment.payment_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE receipt_subscription (receipt_id UUID NOT NULL, subscription_id UUID NOT NULL, PRIMARY KEY(receipt_id, subscription_id))');
        $this->addSql('CREATE INDEX IDX_32952A5C2B5CA896 ON receipt_subscription (receipt_id)');
        $this->addSql('CREATE INDEX IDX_32952A5C9A1887DC ON receipt_subscription (subscription_id)');
        $this->addSql('COMMENT ON COLUMN receipt_subscription.receipt_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN receipt_subscription.subscription_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE receipt_line (id UUID NOT NULL, receipt_id UUID DEFAULT NULL, currency VARCHAR(255) NOT NULL, total INT NOT NULL, sub_total INT NOT NULL, vat_total INT NOT NULL, description VARCHAR(255) DEFAULT NULL, vat_percentage DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_476F8F7A2B5CA896 ON receipt_line (receipt_id)');
        $this->addSql('COMMENT ON COLUMN receipt_line.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN receipt_line.receipt_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE refund (id UUID NOT NULL, payment_id UUID DEFAULT NULL, customer_id UUID DEFAULT NULL, billing_admin_id UUID DEFAULT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, external_reference VARCHAR(255) NOT NULL, reason VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5B2C14584C3A3BB ON refund (payment_id)');
        $this->addSql('CREATE INDEX IDX_5B2C14589395C3F3 ON refund (customer_id)');
        $this->addSql('CREATE INDEX IDX_5B2C14587CF7EBEC ON refund (billing_admin_id)');
        $this->addSql('COMMENT ON COLUMN refund.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN refund.payment_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN refund.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN refund.billing_admin_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE refund_created_process (id UUID NOT NULL, refund_id UUID DEFAULT NULL, state VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, error VARCHAR(255) DEFAULT NULL, has_error BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C12A211C189801D5 ON refund_created_process (refund_id)');
        $this->addSql('COMMENT ON COLUMN refund_created_process.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN refund_created_process.refund_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE settings (id UUID NOT NULL, tag VARCHAR(255) NOT NULL, notification_settings_send_customer_notifications BOOLEAN DEFAULT NULL, notification_settings_emsp VARCHAR(255) DEFAULT NULL, notification_settings_emsp_api_key VARCHAR(255) DEFAULT NULL, notification_settings_emsp_api_url VARCHAR(255) DEFAULT NULL, notification_settings_emsp_domain VARCHAR(255) DEFAULT NULL, notification_settings_default_outgoing_email VARCHAR(255) DEFAULT NULL, system_settings_webhook_url VARCHAR(255) DEFAULT NULL, system_settings_invoice_number_generation VARCHAR(255) DEFAULT NULL, system_settings_default_invoice_due_time VARCHAR(255) DEFAULT NULL, system_settings_subsequential_number INT DEFAULT NULL, system_settings_system_url VARCHAR(255) DEFAULT NULL, system_settings_timezone VARCHAR(255) DEFAULT NULL, system_settings_use_stripe_billing BOOLEAN NOT NULL, system_settings_webhook_external_reference VARCHAR(255) DEFAULT NULL, system_settings_webhook_secret VARCHAR(255) DEFAULT NULL, system_settings_main_currency VARCHAR(255) NOT NULL, system_settings_update_available BOOLEAN NOT NULL, system_settings_update_available_dismissed BOOLEAN DEFAULT NULL, onboarding_settings_has_stripe_imports BOOLEAN DEFAULT NULL, tax_settings_tax_customers_with_tax_numbers BOOLEAN DEFAULT NULL, tax_settings_european_business_tax_rules BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN settings.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_cached_stats (id UUID NOT NULL, type VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, value INT NOT NULL, currency VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_68063FAB5E237E06 ON stats_cached_stats (name)');
        $this->addSql('COMMENT ON COLUMN stats_cached_stats.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_charge_back_amount_daily (id UUID NOT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_66414E71BB8273378EB61006E5A02990 ON stats_charge_back_amount_daily (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_charge_back_amount_daily.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_charge_back_amount_monthly (id UUID NOT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_93F3F329BB8273378EB61006E5A02990 ON stats_charge_back_amount_monthly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_charge_back_amount_monthly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_charge_back_amount_yearly (id UUID NOT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_72CED1F5BB8273378EB61006E5A02990 ON stats_charge_back_amount_yearly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_charge_back_amount_yearly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_customer_creation_daily (id UUID NOT NULL, count INT NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F057DF77BB8273378EB61006E5A02990 ON stats_customer_creation_daily (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_customer_creation_daily.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_customer_creation_monthly (id UUID NOT NULL, count INT NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_42A1616BBB8273378EB61006E5A02990 ON stats_customer_creation_monthly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_customer_creation_monthly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_customer_creation_yearly (id UUID NOT NULL, count INT NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9B3B6251BB8273378EB61006E5A02990 ON stats_customer_creation_yearly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_customer_creation_yearly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_payment_amount_daily (id UUID NOT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A291DA1ABB8273378EB61006E5A02990 ON stats_payment_amount_daily (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_payment_amount_daily.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_payment_amount_monthly (id UUID NOT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E298D2C8BB8273378EB61006E5A02990 ON stats_payment_amount_monthly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_payment_amount_monthly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_payment_amount_yearly (id UUID NOT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A86AB9B1BB8273378EB61006E5A02990 ON stats_payment_amount_yearly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_payment_amount_yearly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_refund_amount_daily (id UUID NOT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_20D50675BB8273378EB61006E5A02990 ON stats_refund_amount_daily (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_refund_amount_daily.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_refund_amount_monthly (id UUID NOT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8F98B91BBB8273378EB61006E5A02990 ON stats_refund_amount_monthly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_refund_amount_monthly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_refund_amount_yearly (id UUID NOT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75E581A4BB8273378EB61006E5A02990 ON stats_refund_amount_yearly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_refund_amount_yearly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_subscription_cancellation_daily (id UUID NOT NULL, count INT NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5272A11FBB8273378EB61006E5A02990 ON stats_subscription_cancellation_daily (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_subscription_cancellation_daily.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_subscription_cancellation_monthly (id UUID NOT NULL, count INT NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_58387EDABB8273378EB61006E5A02990 ON stats_subscription_cancellation_monthly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_subscription_cancellation_monthly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_subscription_cancellation_yearly (id UUID NOT NULL, count INT NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D8F0AE45BB8273378EB61006E5A02990 ON stats_subscription_cancellation_yearly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_subscription_cancellation_yearly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_subscription_count_daily (id UUID NOT NULL, count INT NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1B557083BB8273378EB61006E5A02990 ON stats_subscription_count_daily (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_subscription_count_daily.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_subscription_count_monthly (id UUID NOT NULL, count INT NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_741810A9BB8273378EB61006E5A02990 ON stats_subscription_count_monthly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_subscription_count_monthly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_subscription_count_yearly (id UUID NOT NULL, count INT NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_210056FBBB8273378EB61006E5A02990 ON stats_subscription_count_yearly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_subscription_count_yearly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_subscription_daily (id UUID NOT NULL, count INT NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5B72B37DBB8273378EB61006E5A02990 ON stats_subscription_daily (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_subscription_daily.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_subscription_monthly (id UUID NOT NULL, count INT NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FC4A0FB7BB8273378EB61006E5A02990 ON stats_subscription_monthly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_subscription_monthly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stats_subscription_yearly (id UUID NOT NULL, count INT NOT NULL, year INT NOT NULL, month INT NOT NULL, day INT NOT NULL, date DATE NOT NULL, brand_code VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7B45AE23BB8273378EB61006E5A02990 ON stats_subscription_yearly (year, month, day)');
        $this->addSql('COMMENT ON COLUMN stats_subscription_yearly.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE stripe_import (id UUID NOT NULL, state VARCHAR(255) NOT NULL, last_id VARCHAR(255) DEFAULT NULL, complete BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, error VARCHAR(255) DEFAULT NULL, attempts INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3503B3214267D023 ON stripe_import (complete)');
        $this->addSql('COMMENT ON COLUMN stripe_import.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE subscription (id UUID NOT NULL, payment_details_id UUID DEFAULT NULL, customer_id UUID DEFAULT NULL, price_id UUID DEFAULT NULL, subscription_plan_id UUID DEFAULT NULL, plan_name VARCHAR(255) DEFAULT NULL, payment_schedule VARCHAR(255) DEFAULT NULL, seats INT DEFAULT NULL, active BOOLEAN DEFAULT NULL, status VARCHAR(255) NOT NULL, amount INT DEFAULT NULL, has_trial BOOLEAN NOT NULL, trial_length_days INT DEFAULT NULL, currency VARCHAR(255) DEFAULT NULL, main_external_reference VARCHAR(255) DEFAULT NULL, main_external_reference_details_url VARCHAR(255) DEFAULT NULL, child_external_reference VARCHAR(255) DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, start_of_current_period TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A3C664D38EEC86F7 ON subscription (payment_details_id)');
        $this->addSql('CREATE INDEX IDX_A3C664D39395C3F3 ON subscription (customer_id)');
        $this->addSql('CREATE INDEX IDX_A3C664D3D614C7E7 ON subscription (price_id)');
        $this->addSql('CREATE INDEX IDX_A3C664D39B8CE200 ON subscription (subscription_plan_id)');
        $this->addSql('COMMENT ON COLUMN subscription.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscription.payment_details_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscription.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscription.price_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscription.subscription_plan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE subscription_payment (subscription_id UUID NOT NULL, payment_id UUID NOT NULL, PRIMARY KEY(subscription_id, payment_id))');
        $this->addSql('CREATE INDEX IDX_1E3D64969A1887DC ON subscription_payment (subscription_id)');
        $this->addSql('CREATE INDEX IDX_1E3D64964C3A3BB ON subscription_payment (payment_id)');
        $this->addSql('COMMENT ON COLUMN subscription_payment.subscription_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscription_payment.payment_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE subscription_creation (id UUID NOT NULL, subscription_id UUID DEFAULT NULL, state VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, error VARCHAR(255) DEFAULT NULL, has_error BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3040DA589A1887DC ON subscription_creation (subscription_id)');
        $this->addSql('COMMENT ON COLUMN subscription_creation.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscription_creation.subscription_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE subscription_feature (id UUID NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6CC295FD77153098 ON subscription_feature (code)');
        $this->addSql('COMMENT ON COLUMN subscription_feature.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE subscription_plan (id UUID NOT NULL, product_id UUID DEFAULT NULL, public BOOLEAN NOT NULL, name VARCHAR(255) NOT NULL, code_name VARCHAR(255) DEFAULT NULL, external_reference VARCHAR(255) DEFAULT NULL, payment_provider_details_url VARCHAR(255) DEFAULT NULL, per_seat BOOLEAN DEFAULT NULL, is_free BOOLEAN DEFAULT NULL, user_count INT DEFAULT NULL, has_trial BOOLEAN DEFAULT NULL, trial_length_days INT DEFAULT NULL, deleted BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EA664B6368C814C7 ON subscription_plan (code_name)');
        $this->addSql('CREATE INDEX IDX_EA664B634584665A ON subscription_plan (product_id)');
        $this->addSql('COMMENT ON COLUMN subscription_plan.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscription_plan.product_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE subscription_plan_subscription_feature (subscription_plan_id UUID NOT NULL, subscription_feature_id UUID NOT NULL, PRIMARY KEY(subscription_plan_id, subscription_feature_id))');
        $this->addSql('CREATE INDEX IDX_63CBB01D9B8CE200 ON subscription_plan_subscription_feature (subscription_plan_id)');
        $this->addSql('CREATE INDEX IDX_63CBB01DA201F81C ON subscription_plan_subscription_feature (subscription_feature_id)');
        $this->addSql('COMMENT ON COLUMN subscription_plan_subscription_feature.subscription_plan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscription_plan_subscription_feature.subscription_feature_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE subscription_plan_price (subscription_plan_id UUID NOT NULL, price_id UUID NOT NULL, PRIMARY KEY(subscription_plan_id, price_id))');
        $this->addSql('CREATE INDEX IDX_5B8B27409B8CE200 ON subscription_plan_price (subscription_plan_id)');
        $this->addSql('CREATE INDEX IDX_5B8B2740D614C7E7 ON subscription_plan_price (price_id)');
        $this->addSql('COMMENT ON COLUMN subscription_plan_price.subscription_plan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscription_plan_price.price_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE subscription_plan_limit (id UUID NOT NULL, subscription_feature_id UUID DEFAULT NULL, subscription_plan_id UUID DEFAULT NULL, limit_number INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EED5EDF9A201F81C ON subscription_plan_limit (subscription_feature_id)');
        $this->addSql('CREATE INDEX IDX_EED5EDF99B8CE200 ON subscription_plan_limit (subscription_plan_id)');
        $this->addSql('COMMENT ON COLUMN subscription_plan_limit.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscription_plan_limit.subscription_feature_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscription_plan_limit.subscription_plan_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE subscription_seat_modification (id UUID NOT NULL, subscription_id UUID DEFAULT NULL, type VARCHAR(255) NOT NULL, change_value INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E532907B9A1887DC ON subscription_seat_modification (subscription_id)');
        $this->addSql('COMMENT ON COLUMN subscription_seat_modification.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscription_seat_modification.subscription_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE templates (id UUID NOT NULL, name VARCHAR(255) NOT NULL, content TEXT NOT NULL, brand VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN templates.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE users (id UUID NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, confirmation_code VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, activated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deactivated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_confirmed BOOLEAN NOT NULL, is_deleted BOOLEAN NOT NULL, roles TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN users.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN users.roles IS \'(DC2Type:simple_array)\'');
        $this->addSql('CREATE TABLE vouchers (id UUID NOT NULL, billing_admin_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, entry_type VARCHAR(255) NOT NULL, percentage INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, entry_event VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, disabled BOOLEAN NOT NULL, external_reference VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_931507487CF7EBEC ON vouchers (billing_admin_id)');
        $this->addSql('COMMENT ON COLUMN vouchers.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN vouchers.billing_admin_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE vouchers_amount (id UUID NOT NULL, voucher_id UUID DEFAULT NULL, amount INT NOT NULL, currency VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1A86CADF28AA1B6F ON vouchers_amount (voucher_id)');
        $this->addSql('COMMENT ON COLUMN vouchers_amount.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN vouchers_amount.voucher_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE vouchers_application (id UUID NOT NULL, voucher_id UUID DEFAULT NULL, customer_id UUID DEFAULT NULL, applied_by_id UUID DEFAULT NULL, used BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D72D8FE528AA1B6F ON vouchers_application (voucher_id)');
        $this->addSql('CREATE INDEX IDX_D72D8FE59395C3F3 ON vouchers_application (customer_id)');
        $this->addSql('CREATE INDEX IDX_D72D8FE54B8DEE4D ON vouchers_application (applied_by_id)');
        $this->addSql('COMMENT ON COLUMN vouchers_application.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN vouchers_application.voucher_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN vouchers_application.customer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN vouchers_application.applied_by_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE webhook_endpoint (id UUID NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN webhook_endpoint.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE webhook_event (id UUID NOT NULL, type VARCHAR(255) NOT NULL, payload TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN webhook_event.id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE webhook_event_response (id UUID NOT NULL, event_id UUID DEFAULT NULL, endpoint_id UUID DEFAULT NULL, url VARCHAR(255) NOT NULL, status_code INT DEFAULT NULL, body TEXT DEFAULT NULL, processing_time DOUBLE PRECISION NOT NULL, error_message VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FB4F885B71F7E88B ON webhook_event_response (event_id)');
        $this->addSql('CREATE INDEX IDX_FB4F885B21AF7E36 ON webhook_event_response (endpoint_id)');
        $this->addSql('COMMENT ON COLUMN webhook_event_response.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN webhook_event_response.event_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN webhook_event_response.endpoint_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE OR REPLACE FUNCTION notify_messenger_messages() RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify(\'messenger_messages\', NEW.queue_name::text);
                RETURN NEW;
            END;
        $$ LANGUAGE plpgsql;');
        $this->addSql('DROP TRIGGER IF EXISTS notify_trigger ON messenger_messages;');
        $this->addSql('CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON messenger_messages FOR EACH ROW EXECUTE PROCEDURE notify_messenger_messages();');
        $this->addSql('ALTER TABLE cancellation_requests ADD CONSTRAINT FK_9E258B3E9A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cancellation_requests ADD CONSTRAINT FK_9E258B3E7CF7EBEC FOREIGN KEY (billing_admin_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE charge_back ADD CONSTRAINT FK_250DACE84C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE charge_back ADD CONSTRAINT FK_250DACE89395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE charge_back_creation ADD CONSTRAINT FK_3394E461BDB3CB55 FOREIGN KEY (charge_back_id) REFERENCES charge_back (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checkout ADD CONSTRAINT FK_AF382D4E9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checkout ADD CONSTRAINT FK_AF382D4E38C5B87D FOREIGN KEY (brand_settings_id) REFERENCES brand_settings (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checkout ADD CONSTRAINT FK_AF382D4EB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checkout_line ADD CONSTRAINT FK_3A4D4128146D8724 FOREIGN KEY (checkout_id) REFERENCES checkout (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checkout_line ADD CONSTRAINT FK_3A4D41289B8CE200 FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checkout_line ADD CONSTRAINT FK_3A4D4128D614C7E7 FOREIGN KEY (price_id) REFERENCES price (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checkout_session ADD CONSTRAINT FK_2C2F31AD9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checkout_session ADD CONSTRAINT FK_2C2F31AD146D8724 FOREIGN KEY (checkout_id) REFERENCES checkout (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checkout_session_subscription ADD CONSTRAINT FK_622CEAC2DA6D31C4 FOREIGN KEY (checkout_session_id) REFERENCES checkout_session (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checkout_session_subscription ADD CONSTRAINT FK_622CEAC29A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checkout_session_line ADD CONSTRAINT FK_46316A7DDA6D31C4 FOREIGN KEY (checkout_session_id) REFERENCES checkout_session (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checkout_session_line ADD CONSTRAINT FK_46316A7D9B8CE200 FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checkout_session_line ADD CONSTRAINT FK_46316A7DD614C7E7 FOREIGN KEY (price_id) REFERENCES price (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFE9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFE7CF7EBEC FOREIGN KEY (billing_admin_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customers ADD CONSTRAINT FK_62534E2138C5B87D FOREIGN KEY (brand_settings_id) REFERENCES brand_settings (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE email_templates ADD CONSTRAINT FK_6023E2A544F5D008 FOREIGN KEY (brand_id) REFERENCES brand_settings (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expiring_card_process ADD CONSTRAINT FK_CD6C5DF9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE expiring_card_process ADD CONSTRAINT FK_CD6C5DF538594CA FOREIGN KEY (payment_card_id) REFERENCES payment_card (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE forgot_password_code ADD CONSTRAINT FK_B30A7571A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invite_codes ADD CONSTRAINT FK_E8D89FB2A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invite_codes ADD CONSTRAINT FK_E8D89FB2C58DAD6E FOREIGN KEY (invited_user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517449395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invoice_subscription ADD CONSTRAINT FK_1C014BA72989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invoice_subscription ADD CONSTRAINT FK_1C014BA79A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invoice_payment ADD CONSTRAINT FK_9FF1B2DE2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invoice_payment ADD CONSTRAINT FK_9FF1B2DE4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invoice_line ADD CONSTRAINT FK_D3D1D6932989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invoice_process ADD CONSTRAINT FK_74C42E459395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invoice_process ADD CONSTRAINT FK_74C42E452989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mass_subscription_change ADD CONSTRAINT FK_A63C0CACF1B966A3 FOREIGN KEY (target_subscription_plan_id) REFERENCES subscription_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mass_subscription_change ADD CONSTRAINT FK_A63C0CAC6C4D9255 FOREIGN KEY (new_subscription_plan_id) REFERENCES subscription_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mass_subscription_change ADD CONSTRAINT FK_A63C0CACCBF178E FOREIGN KEY (target_price_id) REFERENCES price (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mass_subscription_change ADD CONSTRAINT FK_A63C0CAC917D4BCB FOREIGN KEY (new_price_id) REFERENCES price (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mass_subscription_change ADD CONSTRAINT FK_A63C0CAC38C5B87D FOREIGN KEY (brand_settings_id) REFERENCES brand_settings (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mass_subscription_change ADD CONSTRAINT FK_A63C0CACB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_subscription ADD CONSTRAINT FK_C536D3C94C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_subscription ADD CONSTRAINT FK_C536D3C99A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_attempt ADD CONSTRAINT FK_1A50C8C9395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_attempt ADD CONSTRAINT FK_1A50C8C2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_attempt_subscription ADD CONSTRAINT FK_A9AFAA2384673FBE FOREIGN KEY (payment_attempt_id) REFERENCES payment_attempt (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_attempt_subscription ADD CONSTRAINT FK_A9AFAA239A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_card ADD CONSTRAINT FK_37970FA79395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_creation ADD CONSTRAINT FK_1728C71C4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_failure_process ADD CONSTRAINT FK_F939A84884673FBE FOREIGN KEY (payment_attempt_id) REFERENCES payment_attempt (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment_failure_process ADD CONSTRAINT FK_F939A8489395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE price ADD CONSTRAINT FK_CAC822D94584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quote ADD CONSTRAINT FK_6B71CBF49395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quote ADD CONSTRAINT FK_6B71CBF4B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quote_subscription ADD CONSTRAINT FK_14273BD5DB805178 FOREIGN KEY (quote_id) REFERENCES quote (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quote_subscription ADD CONSTRAINT FK_14273BD59A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quote_line ADD CONSTRAINT FK_43F3EB7CDB805178 FOREIGN KEY (quote_id) REFERENCES quote (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quote_line ADD CONSTRAINT FK_43F3EB7C9B8CE200 FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quote_line ADD CONSTRAINT FK_43F3EB7CD614C7E7 FOREIGN KEY (price_id) REFERENCES price (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE receipt ADD CONSTRAINT FK_5399B6459395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE receipt_payment ADD CONSTRAINT FK_7E6221F32B5CA896 FOREIGN KEY (receipt_id) REFERENCES receipt (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE receipt_payment ADD CONSTRAINT FK_7E6221F34C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE receipt_subscription ADD CONSTRAINT FK_32952A5C2B5CA896 FOREIGN KEY (receipt_id) REFERENCES receipt (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE receipt_subscription ADD CONSTRAINT FK_32952A5C9A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE receipt_line ADD CONSTRAINT FK_476F8F7A2B5CA896 FOREIGN KEY (receipt_id) REFERENCES receipt (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT FK_5B2C14584C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT FK_5B2C14589395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refund ADD CONSTRAINT FK_5B2C14587CF7EBEC FOREIGN KEY (billing_admin_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refund_created_process ADD CONSTRAINT FK_C12A211C189801D5 FOREIGN KEY (refund_id) REFERENCES refund (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D38EEC86F7 FOREIGN KEY (payment_details_id) REFERENCES payment_card (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D39395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3D614C7E7 FOREIGN KEY (price_id) REFERENCES price (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D39B8CE200 FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_payment ADD CONSTRAINT FK_1E3D64969A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_payment ADD CONSTRAINT FK_1E3D64964C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_creation ADD CONSTRAINT FK_3040DA589A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_plan ADD CONSTRAINT FK_EA664B634584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_plan_subscription_feature ADD CONSTRAINT FK_63CBB01D9B8CE200 FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_plan_subscription_feature ADD CONSTRAINT FK_63CBB01DA201F81C FOREIGN KEY (subscription_feature_id) REFERENCES subscription_feature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_plan_price ADD CONSTRAINT FK_5B8B27409B8CE200 FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_plan_price ADD CONSTRAINT FK_5B8B2740D614C7E7 FOREIGN KEY (price_id) REFERENCES price (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_plan_limit ADD CONSTRAINT FK_EED5EDF9A201F81C FOREIGN KEY (subscription_feature_id) REFERENCES subscription_feature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_plan_limit ADD CONSTRAINT FK_EED5EDF99B8CE200 FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription_seat_modification ADD CONSTRAINT FK_E532907B9A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vouchers ADD CONSTRAINT FK_931507487CF7EBEC FOREIGN KEY (billing_admin_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vouchers_amount ADD CONSTRAINT FK_1A86CADF28AA1B6F FOREIGN KEY (voucher_id) REFERENCES vouchers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vouchers_application ADD CONSTRAINT FK_D72D8FE528AA1B6F FOREIGN KEY (voucher_id) REFERENCES vouchers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vouchers_application ADD CONSTRAINT FK_D72D8FE59395C3F3 FOREIGN KEY (customer_id) REFERENCES customers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vouchers_application ADD CONSTRAINT FK_D72D8FE54B8DEE4D FOREIGN KEY (applied_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE webhook_event_response ADD CONSTRAINT FK_FB4F885B71F7E88B FOREIGN KEY (event_id) REFERENCES webhook_event (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE webhook_event_response ADD CONSTRAINT FK_FB4F885B21AF7E36 FOREIGN KEY (endpoint_id) REFERENCES webhook_endpoint (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE cancellation_requests DROP CONSTRAINT FK_9E258B3E9A1887DC');
        $this->addSql('ALTER TABLE cancellation_requests DROP CONSTRAINT FK_9E258B3E7CF7EBEC');
        $this->addSql('ALTER TABLE charge_back DROP CONSTRAINT FK_250DACE84C3A3BB');
        $this->addSql('ALTER TABLE charge_back DROP CONSTRAINT FK_250DACE89395C3F3');
        $this->addSql('ALTER TABLE charge_back_creation DROP CONSTRAINT FK_3394E461BDB3CB55');
        $this->addSql('ALTER TABLE checkout DROP CONSTRAINT FK_AF382D4E9395C3F3');
        $this->addSql('ALTER TABLE checkout DROP CONSTRAINT FK_AF382D4E38C5B87D');
        $this->addSql('ALTER TABLE checkout DROP CONSTRAINT FK_AF382D4EB03A8386');
        $this->addSql('ALTER TABLE checkout_line DROP CONSTRAINT FK_3A4D4128146D8724');
        $this->addSql('ALTER TABLE checkout_line DROP CONSTRAINT FK_3A4D41289B8CE200');
        $this->addSql('ALTER TABLE checkout_line DROP CONSTRAINT FK_3A4D4128D614C7E7');
        $this->addSql('ALTER TABLE checkout_session DROP CONSTRAINT FK_2C2F31AD9395C3F3');
        $this->addSql('ALTER TABLE checkout_session DROP CONSTRAINT FK_2C2F31AD146D8724');
        $this->addSql('ALTER TABLE checkout_session_subscription DROP CONSTRAINT FK_622CEAC2DA6D31C4');
        $this->addSql('ALTER TABLE checkout_session_subscription DROP CONSTRAINT FK_622CEAC29A1887DC');
        $this->addSql('ALTER TABLE checkout_session_line DROP CONSTRAINT FK_46316A7DDA6D31C4');
        $this->addSql('ALTER TABLE checkout_session_line DROP CONSTRAINT FK_46316A7D9B8CE200');
        $this->addSql('ALTER TABLE checkout_session_line DROP CONSTRAINT FK_46316A7DD614C7E7');
        $this->addSql('ALTER TABLE credit DROP CONSTRAINT FK_1CC16EFE9395C3F3');
        $this->addSql('ALTER TABLE credit DROP CONSTRAINT FK_1CC16EFE7CF7EBEC');
        $this->addSql('ALTER TABLE customers DROP CONSTRAINT FK_62534E2138C5B87D');
        $this->addSql('ALTER TABLE email_templates DROP CONSTRAINT FK_6023E2A544F5D008');
        $this->addSql('ALTER TABLE expiring_card_process DROP CONSTRAINT FK_CD6C5DF9395C3F3');
        $this->addSql('ALTER TABLE expiring_card_process DROP CONSTRAINT FK_CD6C5DF538594CA');
        $this->addSql('ALTER TABLE forgot_password_code DROP CONSTRAINT FK_B30A7571A76ED395');
        $this->addSql('ALTER TABLE invite_codes DROP CONSTRAINT FK_E8D89FB2A76ED395');
        $this->addSql('ALTER TABLE invite_codes DROP CONSTRAINT FK_E8D89FB2C58DAD6E');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_906517449395C3F3');
        $this->addSql('ALTER TABLE invoice_subscription DROP CONSTRAINT FK_1C014BA72989F1FD');
        $this->addSql('ALTER TABLE invoice_subscription DROP CONSTRAINT FK_1C014BA79A1887DC');
        $this->addSql('ALTER TABLE invoice_payment DROP CONSTRAINT FK_9FF1B2DE2989F1FD');
        $this->addSql('ALTER TABLE invoice_payment DROP CONSTRAINT FK_9FF1B2DE4C3A3BB');
        $this->addSql('ALTER TABLE invoice_line DROP CONSTRAINT FK_D3D1D6932989F1FD');
        $this->addSql('ALTER TABLE invoice_process DROP CONSTRAINT FK_74C42E459395C3F3');
        $this->addSql('ALTER TABLE invoice_process DROP CONSTRAINT FK_74C42E452989F1FD');
        $this->addSql('ALTER TABLE mass_subscription_change DROP CONSTRAINT FK_A63C0CACF1B966A3');
        $this->addSql('ALTER TABLE mass_subscription_change DROP CONSTRAINT FK_A63C0CAC6C4D9255');
        $this->addSql('ALTER TABLE mass_subscription_change DROP CONSTRAINT FK_A63C0CACCBF178E');
        $this->addSql('ALTER TABLE mass_subscription_change DROP CONSTRAINT FK_A63C0CAC917D4BCB');
        $this->addSql('ALTER TABLE mass_subscription_change DROP CONSTRAINT FK_A63C0CAC38C5B87D');
        $this->addSql('ALTER TABLE mass_subscription_change DROP CONSTRAINT FK_A63C0CACB03A8386');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D9395C3F3');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D2989F1FD');
        $this->addSql('ALTER TABLE payment_subscription DROP CONSTRAINT FK_C536D3C94C3A3BB');
        $this->addSql('ALTER TABLE payment_subscription DROP CONSTRAINT FK_C536D3C99A1887DC');
        $this->addSql('ALTER TABLE payment_attempt DROP CONSTRAINT FK_1A50C8C9395C3F3');
        $this->addSql('ALTER TABLE payment_attempt DROP CONSTRAINT FK_1A50C8C2989F1FD');
        $this->addSql('ALTER TABLE payment_attempt_subscription DROP CONSTRAINT FK_A9AFAA2384673FBE');
        $this->addSql('ALTER TABLE payment_attempt_subscription DROP CONSTRAINT FK_A9AFAA239A1887DC');
        $this->addSql('ALTER TABLE payment_card DROP CONSTRAINT FK_37970FA79395C3F3');
        $this->addSql('ALTER TABLE payment_creation DROP CONSTRAINT FK_1728C71C4C3A3BB');
        $this->addSql('ALTER TABLE payment_failure_process DROP CONSTRAINT FK_F939A84884673FBE');
        $this->addSql('ALTER TABLE payment_failure_process DROP CONSTRAINT FK_F939A8489395C3F3');
        $this->addSql('ALTER TABLE price DROP CONSTRAINT FK_CAC822D94584665A');
        $this->addSql('ALTER TABLE quote DROP CONSTRAINT FK_6B71CBF49395C3F3');
        $this->addSql('ALTER TABLE quote DROP CONSTRAINT FK_6B71CBF4B03A8386');
        $this->addSql('ALTER TABLE quote_subscription DROP CONSTRAINT FK_14273BD5DB805178');
        $this->addSql('ALTER TABLE quote_subscription DROP CONSTRAINT FK_14273BD59A1887DC');
        $this->addSql('ALTER TABLE quote_line DROP CONSTRAINT FK_43F3EB7CDB805178');
        $this->addSql('ALTER TABLE quote_line DROP CONSTRAINT FK_43F3EB7C9B8CE200');
        $this->addSql('ALTER TABLE quote_line DROP CONSTRAINT FK_43F3EB7CD614C7E7');
        $this->addSql('ALTER TABLE receipt DROP CONSTRAINT FK_5399B6459395C3F3');
        $this->addSql('ALTER TABLE receipt_payment DROP CONSTRAINT FK_7E6221F32B5CA896');
        $this->addSql('ALTER TABLE receipt_payment DROP CONSTRAINT FK_7E6221F34C3A3BB');
        $this->addSql('ALTER TABLE receipt_subscription DROP CONSTRAINT FK_32952A5C2B5CA896');
        $this->addSql('ALTER TABLE receipt_subscription DROP CONSTRAINT FK_32952A5C9A1887DC');
        $this->addSql('ALTER TABLE receipt_line DROP CONSTRAINT FK_476F8F7A2B5CA896');
        $this->addSql('ALTER TABLE refund DROP CONSTRAINT FK_5B2C14584C3A3BB');
        $this->addSql('ALTER TABLE refund DROP CONSTRAINT FK_5B2C14589395C3F3');
        $this->addSql('ALTER TABLE refund DROP CONSTRAINT FK_5B2C14587CF7EBEC');
        $this->addSql('ALTER TABLE refund_created_process DROP CONSTRAINT FK_C12A211C189801D5');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D38EEC86F7');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D39395C3F3');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D3D614C7E7');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D39B8CE200');
        $this->addSql('ALTER TABLE subscription_payment DROP CONSTRAINT FK_1E3D64969A1887DC');
        $this->addSql('ALTER TABLE subscription_payment DROP CONSTRAINT FK_1E3D64964C3A3BB');
        $this->addSql('ALTER TABLE subscription_creation DROP CONSTRAINT FK_3040DA589A1887DC');
        $this->addSql('ALTER TABLE subscription_plan DROP CONSTRAINT FK_EA664B634584665A');
        $this->addSql('ALTER TABLE subscription_plan_subscription_feature DROP CONSTRAINT FK_63CBB01D9B8CE200');
        $this->addSql('ALTER TABLE subscription_plan_subscription_feature DROP CONSTRAINT FK_63CBB01DA201F81C');
        $this->addSql('ALTER TABLE subscription_plan_price DROP CONSTRAINT FK_5B8B27409B8CE200');
        $this->addSql('ALTER TABLE subscription_plan_price DROP CONSTRAINT FK_5B8B2740D614C7E7');
        $this->addSql('ALTER TABLE subscription_plan_limit DROP CONSTRAINT FK_EED5EDF9A201F81C');
        $this->addSql('ALTER TABLE subscription_plan_limit DROP CONSTRAINT FK_EED5EDF99B8CE200');
        $this->addSql('ALTER TABLE subscription_seat_modification DROP CONSTRAINT FK_E532907B9A1887DC');
        $this->addSql('ALTER TABLE vouchers DROP CONSTRAINT FK_931507487CF7EBEC');
        $this->addSql('ALTER TABLE vouchers_amount DROP CONSTRAINT FK_1A86CADF28AA1B6F');
        $this->addSql('ALTER TABLE vouchers_application DROP CONSTRAINT FK_D72D8FE528AA1B6F');
        $this->addSql('ALTER TABLE vouchers_application DROP CONSTRAINT FK_D72D8FE59395C3F3');
        $this->addSql('ALTER TABLE vouchers_application DROP CONSTRAINT FK_D72D8FE54B8DEE4D');
        $this->addSql('ALTER TABLE webhook_event_response DROP CONSTRAINT FK_FB4F885B71F7E88B');
        $this->addSql('ALTER TABLE webhook_event_response DROP CONSTRAINT FK_FB4F885B21AF7E36');
        $this->addSql('DROP TABLE api_key');
        $this->addSql('DROP TABLE brand_settings');
        $this->addSql('DROP TABLE cancellation_requests');
        $this->addSql('DROP TABLE charge_back');
        $this->addSql('DROP TABLE charge_back_creation');
        $this->addSql('DROP TABLE checkout');
        $this->addSql('DROP TABLE checkout_line');
        $this->addSql('DROP TABLE checkout_session');
        $this->addSql('DROP TABLE checkout_session_subscription');
        $this->addSql('DROP TABLE checkout_session_line');
        $this->addSql('DROP TABLE credit');
        $this->addSql('DROP TABLE customers');
        $this->addSql('DROP TABLE email_templates');
        $this->addSql('DROP TABLE exchange_rates');
        $this->addSql('DROP TABLE expiring_card_process');
        $this->addSql('DROP TABLE forgot_password_code');
        $this->addSql('DROP TABLE generic_background_task');
        $this->addSql('DROP TABLE invite_codes');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE invoice_subscription');
        $this->addSql('DROP TABLE invoice_payment');
        $this->addSql('DROP TABLE invoice_line');
        $this->addSql('DROP TABLE invoice_process');
        $this->addSql('DROP TABLE mass_subscription_change');
        $this->addSql('DROP TABLE parthenon_export_background_export_requests');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE payment_subscription');
        $this->addSql('DROP TABLE payment_attempt');
        $this->addSql('DROP TABLE payment_attempt_subscription');
        $this->addSql('DROP TABLE payment_card');
        $this->addSql('DROP TABLE payment_creation');
        $this->addSql('DROP TABLE payment_failure_process');
        $this->addSql('DROP TABLE price');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE quote');
        $this->addSql('DROP TABLE quote_subscription');
        $this->addSql('DROP TABLE quote_line');
        $this->addSql('DROP TABLE receipt');
        $this->addSql('DROP TABLE receipt_payment');
        $this->addSql('DROP TABLE receipt_subscription');
        $this->addSql('DROP TABLE receipt_line');
        $this->addSql('DROP TABLE refund');
        $this->addSql('DROP TABLE refund_created_process');
        $this->addSql('DROP TABLE settings');
        $this->addSql('DROP TABLE stats_cached_stats');
        $this->addSql('DROP TABLE stats_charge_back_amount_daily');
        $this->addSql('DROP TABLE stats_charge_back_amount_monthly');
        $this->addSql('DROP TABLE stats_charge_back_amount_yearly');
        $this->addSql('DROP TABLE stats_customer_creation_daily');
        $this->addSql('DROP TABLE stats_customer_creation_monthly');
        $this->addSql('DROP TABLE stats_customer_creation_yearly');
        $this->addSql('DROP TABLE stats_payment_amount_daily');
        $this->addSql('DROP TABLE stats_payment_amount_monthly');
        $this->addSql('DROP TABLE stats_payment_amount_yearly');
        $this->addSql('DROP TABLE stats_refund_amount_daily');
        $this->addSql('DROP TABLE stats_refund_amount_monthly');
        $this->addSql('DROP TABLE stats_refund_amount_yearly');
        $this->addSql('DROP TABLE stats_subscription_cancellation_daily');
        $this->addSql('DROP TABLE stats_subscription_cancellation_monthly');
        $this->addSql('DROP TABLE stats_subscription_cancellation_yearly');
        $this->addSql('DROP TABLE stats_subscription_count_daily');
        $this->addSql('DROP TABLE stats_subscription_count_monthly');
        $this->addSql('DROP TABLE stats_subscription_count_yearly');
        $this->addSql('DROP TABLE stats_subscription_daily');
        $this->addSql('DROP TABLE stats_subscription_monthly');
        $this->addSql('DROP TABLE stats_subscription_yearly');
        $this->addSql('DROP TABLE stripe_import');
        $this->addSql('DROP TABLE subscription');
        $this->addSql('DROP TABLE subscription_payment');
        $this->addSql('DROP TABLE subscription_creation');
        $this->addSql('DROP TABLE subscription_feature');
        $this->addSql('DROP TABLE subscription_plan');
        $this->addSql('DROP TABLE subscription_plan_subscription_feature');
        $this->addSql('DROP TABLE subscription_plan_price');
        $this->addSql('DROP TABLE subscription_plan_limit');
        $this->addSql('DROP TABLE subscription_seat_modification');
        $this->addSql('DROP TABLE templates');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE vouchers');
        $this->addSql('DROP TABLE vouchers_amount');
        $this->addSql('DROP TABLE vouchers_application');
        $this->addSql('DROP TABLE webhook_endpoint');
        $this->addSql('DROP TABLE webhook_event');
        $this->addSql('DROP TABLE webhook_event_response');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
