services:
  _defaults:
    autowire: true
    autoconfigure: true

  twig.security_policy:
    class: Twig\Sandbox\SecurityPolicy
    factory: [ '@BillaBear\Twig\SecurityPolicyFactory', 'create' ]

  template_twig:
    class: Twig\Environment
    arguments:
      - '@twig.loader'  # Assuming twig.loader is the loader service
    calls:
      - method: addExtension
        arguments:
          - '@twig.sandbox'


    # Define the sandbox extension with the custom security policy
  twig.sandbox:
    class: Twig\Extension\SandboxExtension
    arguments:
      - '@twig.security_policy'
      - true

