controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

parthenon_user_controllers:
    prefix: /app
    resource: ../vendor/parthenon/parthenon/src/User/Controller/
    type: annotation

parthenon_payments_controllers:
    prefix: /app
    resource: ../vendor/parthenon/parthenon/src/Payments/Controller/
    type: annotation
