services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    Parthenon\Notification\EmailSenderInterface: '@Parthenon\Notification\Sender\NullEmailSender'

    App\Customer\ExternalRegisterInterface: '@App\Customer\DummyRegister'

    Parthenon\Billing\Obol\ProductRegisterInterface: '@App\Dummy\ProductRegister'
    Parthenon\Billing\Obol\PriceRegisterInterface: '@App\Dummy\ProductRegister'
    Obol\Provider\ProviderInterface: '@App\Dummy\Provider\Provider'
    App\Webhook\Outbound\EventDispatcherInterface: '@App\Webhook\Outbound\EventDispatcher'