services:
    _defaults:
        autowire: true
        autoconfigure: true

    BillaBear\Tests\Behat\:
        resource: '../tests/Behat/*'

    BillaBear\Tests\Mock\:
        resource: '../tests/Mock/*'

    Parthenon\Notification\EmailSenderInterface: '@BillaBear\Tests\Mock\EmailSender'
    BillaBear\Customer\ExternalRegisterInterface: '@BillaBear\Customer\DummyRegister'

    Parthenon\Billing\Obol\ProductRegisterInterface: '@BillaBear\Dummy\ProductRegister'
    Parthenon\Billing\Obol\PriceRegisterInterface: '@BillaBear\Dummy\ProductRegister'
    Obol\Provider\ProviderInterface: '@BillaBear\Dummy\Provider\Provider'
    BillaBear\Webhook\Outbound\EventDispatcherInterface: '@BillaBear\Webhook\Outbound\EventDispatcher'
